# Generated by Django 5.1.2 on 2024-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaartigo_categoriareceita_artigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemreceita',
            name='url_imagem',
            field=models.ImageField(upload_to='receitas/'),
        ),
    ]
