# Generated by Django 5.1.2 on 2024-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagemreceita_url_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemartigo',
            name='url_imagem',
            field=models.ImageField(upload_to='artigos/'),
        ),
    ]
